on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.19'
          check-latest: true

      - name: Verify Dependencies
        run: |
          go mod tidy 
          go mod download
          go mod verify
      
      # Run Go tests in the /tests directory
      - name: Run Go tests
        run: go test -v -count=1 -race ./tests/...